
      let global = globalThis;

      class MessageChannel {
        constructor() {
          this.port1 = new MessagePort();
          this.port2 = new MessagePort();
        }
      }
      class MessagePort {
        constructor() {
          this.onmessage = null;
        }
        postMessage(data) {
          if (this.onmessage) {
            setTimeout(() => this.onmessage({ data }), 0);
          }
        }
      }
      global.MessageChannel = MessageChannel;

      async function handleRequest(context){
        let routeParams = {};
        let pagesFunctionResponse = null;
        const request = context.request;
        const waitUntil = context.waitUntil;
        const urlInfo = new URL(request.url);

        if (urlInfo.pathname !== '/' && urlInfo.pathname.endsWith('/')) {
          urlInfo.pathname = urlInfo.pathname.slice(0, -1);
        }

        let matchedFunc = false;
        
          if('/helloworld' === urlInfo.pathname) {
            matchedFunc = true;
              (() => {
  // functions/helloworld/index.js
  var html = `
  <!DOCTYPE html>
  <body>
    <h1>Hello World</h1>
    <p>This markup was generated by TencentCloud Pages Functions.</p>
  </body>
`;
  function onRequest(context) {
    return new Response(html, {
      headers: {
        "content-type": "text/html; charset=UTF-8",
        "x-edgefunctions-test": "Welcome to use Pages Functions."
      }
    });
  }

        pagesFunctionResponse = onRequest;
      })();
          }
        

        const params = {};
        if (routeParams.id) {
          if (routeParams.mode === 1) {
            const value = urlInfo.pathname.match(routeParams.left);        
            for (let i = 1; i < value.length; i++) {
              params[routeParams.id[i - 1]] = value[i];
            }
          } else {
            const value = urlInfo.pathname.replace(routeParams.left, '');
            const splitedValue = value.split('/');
            if (splitedValue.length === 1) {
              params[routeParams.id] = splitedValue[0];
            } else {
              params[routeParams.id] = splitedValue;
            }
          }
          
        }
        if(!matchedFunc){
          pagesFunctionResponse = function() {
            return new Response(null, {
              status: 404,
              headers: {
                "content-type": "text/html; charset=UTF-8",
                "x-edgefunctions-test": "Welcome to use Pages Functions.",
              },
            });
          }
        }
        return pagesFunctionResponse({request, params, env: {"MallocNanoZone":"0","USER":"jesper","SECURITYSESSIONID":"186a5","COMMAND_MODE":"unix2003","__CFBundleIdentifier":"com.microsoft.VSCode","PATH":"/Users/jesper/.nvm/versions/node/v22.17.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jesper/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand","HOME":"/Users/jesper","SHELL":"/bin/zsh","LaunchInstanceID":"AF6214FF-D5A0-4DD4-9C1C-3127390AA3FD","__CF_USER_TEXT_ENCODING":"0x1F5:0x19:0x34","XPC_SERVICE_NAME":"0","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.CldbhDSkkp/Listeners","XPC_FLAGS":"0x0","LOGNAME":"jesper","TMPDIR":"/var/folders/16/sp3sbp8d33d_6_ygxdp3zkdr0000gn/T/","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","SHLVL":"1","PWD":"/Users/jesper/Desktop/WorkSpace/framework-demo/vue/vue-template-main","OLDPWD":"/Users/jesper/Desktop/WorkSpace/framework-demo/vue/vue-template-main","NVM_CD_FLAGS":"-q","NVM_DIR":"/Users/jesper/.nvm","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.104.2","LANG":"en_US.UTF-8","COLORTERM":"truecolor","GIT_ASKPASS":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh","VSCODE_GIT_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_GIT_ASKPASS_EXTRA_ARGS":"","VSCODE_GIT_ASKPASS_MAIN":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js","VSCODE_GIT_IPC_HANDLE":"/var/folders/16/sp3sbp8d33d_6_ygxdp3zkdr0000gn/T/vscode-git-277e1544ba.sock","VSCODE_INJECTION":"1","ZDOTDIR":"/Users/jesper","USER_ZDOTDIR":"/Users/jesper","TERM":"xterm-256color","VSCODE_PROFILE_INITIALIZED":"1","NVM_BIN":"/Users/jesper/.nvm/versions/node/v22.17.1/bin","NVM_INC":"/Users/jesper/.nvm/versions/node/v22.17.1/include/node","VSCODE_PYTHON_AUTOACTIVATE_GUARD":"1","_":"/Users/jesper/.nvm/versions/node/v22.17.1/bin/edgeone"}, waitUntil });
      }
      addEventListener('fetch', event=>{return event.respondWith(handleRequest({request:event.request,params: {}, env: {"MallocNanoZone":"0","USER":"jesper","SECURITYSESSIONID":"186a5","COMMAND_MODE":"unix2003","__CFBundleIdentifier":"com.microsoft.VSCode","PATH":"/Users/jesper/.nvm/versions/node/v22.17.1/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jesper/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand","HOME":"/Users/jesper","SHELL":"/bin/zsh","LaunchInstanceID":"AF6214FF-D5A0-4DD4-9C1C-3127390AA3FD","__CF_USER_TEXT_ENCODING":"0x1F5:0x19:0x34","XPC_SERVICE_NAME":"0","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.CldbhDSkkp/Listeners","XPC_FLAGS":"0x0","LOGNAME":"jesper","TMPDIR":"/var/folders/16/sp3sbp8d33d_6_ygxdp3zkdr0000gn/T/","ORIGINAL_XDG_CURRENT_DESKTOP":"undefined","SHLVL":"1","PWD":"/Users/jesper/Desktop/WorkSpace/framework-demo/vue/vue-template-main","OLDPWD":"/Users/jesper/Desktop/WorkSpace/framework-demo/vue/vue-template-main","NVM_CD_FLAGS":"-q","NVM_DIR":"/Users/jesper/.nvm","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.104.2","LANG":"en_US.UTF-8","COLORTERM":"truecolor","GIT_ASKPASS":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh","VSCODE_GIT_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_GIT_ASKPASS_EXTRA_ARGS":"","VSCODE_GIT_ASKPASS_MAIN":"/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js","VSCODE_GIT_IPC_HANDLE":"/var/folders/16/sp3sbp8d33d_6_ygxdp3zkdr0000gn/T/vscode-git-277e1544ba.sock","VSCODE_INJECTION":"1","ZDOTDIR":"/Users/jesper","USER_ZDOTDIR":"/Users/jesper","TERM":"xterm-256color","VSCODE_PROFILE_INITIALIZED":"1","NVM_BIN":"/Users/jesper/.nvm/versions/node/v22.17.1/bin","NVM_INC":"/Users/jesper/.nvm/versions/node/v22.17.1/include/node","VSCODE_PYTHON_AUTOACTIVATE_GUARD":"1","_":"/Users/jesper/.nvm/versions/node/v22.17.1/bin/edgeone"}, waitUntil: event.waitUntil }))});